image: registry.gitlab.com/pheix-pool/docker-core-perl6:latest

before_script:
  - raku --version
  - zef update
  - zef --debug --depsonly install git://github.com/ugexe/zef.git
test:
  script:
    - prove6 -v -Ilib ./t/
    - zef --verbose install .
  only:
    - main
    - develop
