name: CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:latest

    steps:
    - uses: actions/checkout@v4

    - name: Raku version
      run: raku -v

    - name: update apt
      run:  apt-get update

    - name: Install libscrypt
      run:  apt-get install -y libscrypt0

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    - name: Run tests
      run: zef test -v --debug .
